name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.rst'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.rst'
      - '*.md'

env:
  POETRY_VIRTUALENVS_CREATE: true
  POETRY_VIRTUALENVS_IN_PROJECT: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Install tools (Poetry)
      uses: Gr1N/setup-poetry@v8
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Verify python version
      run: poetry run python -V
    - name: Install dependencies
      run: poetry install
    - name: Run tests
      run: poetry run invoke test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools (Poetry)
        uses: Gr1N/setup-poetry@v8
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Verify python version
        run: poetry run python -V
      - name: Install dependencies
        run: poetry install
      - name: Run format checks
        run: poetry run invoke format-check

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools (Poetry)
        uses: Gr1N/setup-poetry@v8
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Verify python version
        run: poetry run python -V
      - name: Install dependencies
        run: poetry install
      - name: Run lint checks
        run: poetry run invoke lint

  type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools (Poetry)
        uses: Gr1N/setup-poetry@v8
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Verify python version
        run: poetry run python -V
      - name: Install dependencies
        run: poetry install
      - name: Run type checks
        run: poetry run invoke type
